aws:
    efs:
        mount_point: "/mnt/efs/"
    sqs:
        queue_name: "extractor-to-databank-demo"
        queue_url: "https://sqs.us-east-2.amazonaws.com/721945215539/extractor-to-databank-demo"
    s3:
        json_bucket: "databank-demo-main"
