aws:
    efs:
        mount_point: "/mnt/efs/"
    sqs:
        queue_name: "extractor-to-databank-prod"
        queue_url: "https://sqs.us-east-2.amazonaws.com/721945215539/extractor-to-databank-prod"
    s3:
        json_bucket: "databank-main"
ephemeral_storage_path: "/tmp/extractor/"