aws:
    efs:
        mount_point: "test/efs/"
    sqs:
        queue_name: "extractor-to-databank-test"
        queue_url: "https://sqs.us-east-2.amazonaws.com/721945215539/extractor-to-databank-test"
    s3:
        json_bucket: "databank-test-main"
ephemeral_storage_path: "/test/tmp/extractor/"