on:
  push:
    branches:
    - main
    - stable
    - 'bugfix/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/extractor/Dockerfile-test
          tags: extractor-test
          platforms: linux/arm64